{% set name = "libcloudspawner" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libcloudspawner-{{ version }}.tar.gz
  sha256: 1f754e78faf7321fcc2f4011f62167b13c69d929d8d489600133a4d3c176834e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - jinja2
    - jupyterhub >=4.0.0
    - apache-libcloud

test:
  imports:
    - libcloudspawner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupytercloud-project/jupyterhub-libcloudspawner
  summary: JupyterHub Spawner for clouds
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tristanlt
